Include fcntl.h for F_* and O_* defines
Fixes errors like
utils.c:95:22: error: use of undeclared identifier 'O_WRONLY'

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Reviewed-by: Jan Friesse <jfriesse@redhat.com>
(cherry picked from commit 1a2c72a80ec079f8eb2dadef670773ca3a89dba0)